# Morphometric analysis

This notebook includes code to generate figures and statistical analyses for spinal cord morphometrics in pediatric subjects.

In [227]:
import os
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import plotly.graph_objects as go
from statsmodels.stats.multitest import multipletests
from plotly.subplots import make_subplots
import statsmodels.formula.api as smf
import re

## 1. Load files and prepare data for plotting

### 1.1 Load config file to get path to dataset

In [228]:
# Load config file
with open('../../config/config_preprocessing.yaml' , 'r') as file:
    config = yaml.safe_load(file)

# Get data path from config file
path_data = config['path_data']

### 1.2 Get the `participants.tsv` file from the dataset

In [229]:
# Get path to participants.tsv file
participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')
participants_tsv

    participant_id  age sex    group scan_series  height     weight
0          sub-101   17   M  control    complete  1.7780  68.038855
1          sub-102   15   F  control    complete  1.6256  52.163123
2          sub-103   15   M  control    complete  1.6510  54.431084
3          sub-104   16   F  control    complete  1.6256  52.163123
4          sub-105   13   M  control    complete  1.5494  35.380205
..             ...  ...  ..      ...         ...     ...        ...
131        sub-235   13   M  control  incomplete  1.7272  51.709530
132        sub-236   13   M  control    complete  1.6510  53.523900
133        sub-237   13   M  control    complete  1.6002  45.359237
134        sub-238   15   F  control    complete     NaN        NaN
135        sub-239    6   F  control    complete     NaN        NaN

[136 rows x 7 columns]

### 1.3 Dataframe of subjects included in the pipeline analysis

The following dataframe contains only the subjects that were included in this pipeline analysis.

In [230]:
def get_list_of_subjects_to_include(contrast, path_data, missing_data_subjects):
    """
    This function takes an image contrast (T2w, dwi, etc.), a path to a dataset, and a list of subjects with missing data,
    and returns a list of subjects to include in the analysis.

    The dataset needs to be in BIDS format, and the function will look for the participants.tsv file to get the list of subjects.
    The dataset should also contain an `exclude.yml` file that lists subjects to exclude from the analysis.
    """

    # Get the `participants.tsv` file and read it into a dataframe
    participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')

    # Get all subject IDs from the participants.tsv
    all_subjects = participants_tsv['participant_id'].tolist()

    # Get list of subjects to exclude from the analysis from the `exclude.yml` file
    with open(os.path.join(path_data, 'exclude.yml'), 'r') as file:
        exclude_yml = yaml.safe_load(file)

    exclude_t2star_key = exclude_yml.get(contrast, []) # Extract subjects under contrast key
    exclude_subjects = sorted(set(re.match(r"(sub-\d+)", entry).group(1) for entry in exclude_t2star_key if re.match(r"(sub-\d+)", entry))) # Extract the subject ID 

    # Add the list of subjects with missing data to the exclude_subjects list
    exclude_subjects.extend(missing_data_subjects)
    
    # Remove duplicates (if any), sort and print the list of subjects to exclude from the analysis
    exclude_subjects = sorted(set(exclude_subjects))
    print(f'subjects to exclude : {exclude_subjects}')

    # Compute the list of subjects to include in the analysis 
    include_subjects = [sub for sub in all_subjects if sub not in exclude_subjects]

    # Create a list of participants where the SC tip is visible (remove participants under the `sc-tip` flag in the `exclude.yml`)
    exclude_sc_tip_key = exclude_yml.get("sc-tip", []) # Extract subjects under the "sc-tip" key, corresponding to the list of participants where the sc tip is not visible on the T2w image
    exclude_sc_tip_subjects = sorted(set(re.match(r"(sub-\d+)", entry).group(1) for entry in exclude_sc_tip_key if re.match(r"(sub-\d+)", entry))) # Extract the subject ID 
    include_subjects_with_sc_tip = [sub for sub in include_subjects if sub not in exclude_sc_tip_subjects]

    # Convert the list of included subjects to dataframes
    include_subjects = participants_tsv[participants_tsv['participant_id'].isin(include_subjects)]
    include_subjects_with_sc_tip = participants_tsv[participants_tsv['participant_id'].isin(include_subjects_with_sc_tip)]


    return include_subjects, include_subjects_with_sc_tip

In [231]:
# List of subjects with missing rec-composed T2w data 
missing_t2_subjects = ["sub-217", 
                       "sub-218",
                       "sub-107",
                       "sub-125",
                       "sub-137",
                       "sub-144",
                       "sub-152",
                       "sub-221"]

# Get the list of subjects to include in the analysis
include_t2_subjects, include_subjects_with_sc_tip = get_list_of_subjects_to_include('t2w', path_data, missing_t2_subjects)
include_t2_subjects.to_csv(os.path.join('../tables/morphometrics/include_t2w_subjects.csv'), sep='\t', index=False)
include_subjects_with_sc_tip .to_csv(os.path.join('../tables/morphometrics/include_t2w_subjects_with_sc_tip.csv'), sep='\t', index=False)

print(include_t2_subjects.shape[0], "subjects to include in the T2w morphometric analysis\n")
print(f"\n list of subjects to include : \n {include_t2_subjects['participant_id'].tolist()}\n")

print(include_subjects_with_sc_tip .shape[0], "subjects with SC tip to include in the T2w morphometric analysis")
print(f"\n list of subjects with SC tip to include : \n {include_t2_subjects['participant_id'].tolist()}")

subjects to exclude : ['sub-107', 'sub-108', 'sub-110', 'sub-111', 'sub-121', 'sub-125', 'sub-133', 'sub-136', 'sub-137', 'sub-141', 'sub-144', 'sub-150', 'sub-152', 'sub-159', 'sub-160', 'sub-161', 'sub-163', 'sub-165', 'sub-167', 'sub-168', 'sub-169', 'sub-170', 'sub-177', 'sub-179', 'sub-186', 'sub-190', 'sub-191', 'sub-193', 'sub-198', 'sub-203', 'sub-208', 'sub-209', 'sub-211', 'sub-213', 'sub-214', 'sub-217', 'sub-218', 'sub-221', 'sub-236', 'sub-238']
96 subjects to include in the T2w morphometric analysis


 list of subjects to include :
 ['sub-101', 'sub-102', 'sub-103', 'sub-104', 'sub-105', 'sub-106', 'sub-109', 'sub-112', 'sub-113', 'sub-114', 'sub-115', 'sub-116', 'sub-117', 'sub-118', 'sub-119', 'sub-120', 'sub-122', 'sub-123', 'sub-124', 'sub-126', 'sub-127', 'sub-128', 'sub-129', 'sub-130', 'sub-131', 'sub-132', 'sub-134', 'sub-135', 'sub-138', 'sub-139', 'sub-140', 'sub-142', 'sub-143', 'sub-145', 'sub-146', 'sub-147', 'sub-148', 'sub-149', 'sub-151', 'sub-153', 'sub-154', 'sub-155', 'sub-156', 'sub-158', 'sub-162', 'sub-164', 'sub-166', 'sub-171', 'sub-172', 'sub-173', 'sub-174', 'sub-175', 'sub-176', 'sub-178', 'sub-180', 'sub-181', 'sub-182', 'sub-183', 'sub-184', 'sub-185', 'sub-188', 'sub-189', 'sub-192', 'sub-194', 'sub-196', 'sub-197', 'sub-199', 'sub-200', 'sub-201', 'sub-202', 'sub-204', 'sub-205', 'sub-206', 'sub-207', 'sub-210', 'sub-212', 'sub-215', 'sub-216', 'sub-219', 'sub-220', 'sub-222', 'sub-223', 'sub-224', 'sub-225', 'sub-226', 'sub-227', 'sub-228', 'sub-229', 'sub-230', 'sub-231', 'sub-232', 'sub-233', 'sub-234', 'sub-235', 'sub-237', 'sub-239']

79 subjects with SC tip to include in the T2w morphometric analysis

 list of subjects with SC tip to include :
 ['sub-101', 'sub-102', 'sub-103', 'sub-104', 'sub-105', 'sub-106', 'sub-109', 'sub-112', 'sub-113', 'sub-114', 'sub-115', 'sub-116', 'sub-117', 'sub-118', 'sub-119', 'sub-120', 'sub-122', 'sub-123', 'sub-124', 'sub-126', 'sub-127', 'sub-128', 'sub-129', 'sub-130', 'sub-131', 'sub-132', 'sub-134', 'sub-135', 'sub-138', 'sub-139', 'sub-140', 'sub-142', 'sub-143', 'sub-145', 'sub-146', 'sub-147', 'sub-148', 'sub-149', 'sub-151', 'sub-153', 'sub-154', 'sub-155', 'sub-156', 'sub-158', 'sub-162', 'sub-164', 'sub-166', 'sub-171', 'sub-172', 'sub-173', 'sub-174', 'sub-175', 'sub-176', 'sub-178', 'sub-180', 'sub-181', 'sub-182', 'sub-183', 'sub-184', 'sub-185', 'sub-188', 'sub-189', 'sub-192', 'sub-194', 'sub-196', 'sub-197', 'sub-199', 'sub-200', 'sub-201', 'sub-202', 'sub-204', 'sub-205', 'sub-206', 'sub-207', 'sub-210', 'sub-212', 'sub-215', 'sub-216', 'sub-219', 'sub-220', 'sub-222', 'sub-223', 'sub-224', 'sub-225', 'sub-226', 'sub-227', 'sub-228', 'sub-229', 'sub-230', 'sub-231', 'sub-232', 'sub-233', 'sub-234', 'sub-235', 'sub-237', 'sub-239']

### 1.4 Plot demographics

This function plots the age and sex distribution of the subjects included in a pipeline analysis, according to the include list generated above.

In [232]:
def plot_demographics(df):
    """
    This function plots the demographic information of participants, given a dataframe with the list of subjects to include in the analysis.
    """

    # Sort by sex
    df_M = df[df['sex'] == 'M']
    df_F = df[df['sex'] == 'F']

    # Round down age to nearest month 
    df['age'] = np.floor(df['age']) 

    # Create subplot
    fig = make_subplots(rows=1, cols=1)

    # Add histogram for female subjects
    fig.add_trace(go.Histogram(
        x=df_F['age'], 
        name='F', 
        marker=dict(color= "#D19D88"),
        opacity=1.0,
        legendgroup='F',
        ),
        row=1, col=1
    )

    # Add histogram for male subjects
    fig.add_trace(go.Histogram(
        x=df_M['age'], 
        name='M', 
        
        marker=dict(color="#5C8EA1"),
        opacity=1.0,
        legendgroup='M',
        ), 
        row=1, col=1
    )

    # Define age tick range
    tick_vals = list(range(6, 18)) 

    # Update layout
    fig.update_layout(
        width=900,
        height=500,
        font=dict(family='Arial', size=20, color='black'), 
        legend=dict(
            orientation="h", 
            yanchor="bottom", 
            y=1.0, 
            xanchor="center",  
            x=0.5,
        ),
        xaxis=dict(
            range=[5, 18],  # Set x-axis range from 6 to 17
        ),
        plot_bgcolor='white',
        barmode='stack',
        bargap=0.3,  
        xaxis_title='Age (years)',
        xaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        yaxis_title='Number of Subjects',
        yaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        xaxis_title_standoff=50, 
    )

    fig.update_xaxes(
        tickmode='array',
        tickvals=tick_vals,
        showgrid=False,
        gridwidth=1
    )

    fig.update_yaxes(
        showgrid=True,             # Horizontal grid lines
        gridcolor='lightgrey',
        gridwidth=1
    )

    # Set bin size to 1 year
    fig.update_traces(xbins=dict(size=1))

    fig.show()

In [233]:
# Plot demographics for included subjects in T2w analysis
plot_demographics(include_t2_subjects)

### 1.5 Create dataframe containing interpolated morphometrics
Load the CSV files containing interpolated morphometrics (ending with `_interpolated_morphometrics.csv`) and create a single dataframe containing all participants

In [234]:
# Path to morphometric
morphometric_results_dir = '../tables/morphometrics/'

# Path to participants.tsv
participants_info_path = os.path.join(path_data, 'participants.tsv')

# Initialize an empty DataFrame to store morphometric values
interpolated_morphometrics_df = pd.DataFrame()

# Load the CSV files containing morphometric values of each subject and add to a single dataframe
for file in os.listdir(morphometric_results_dir):
    if file.endswith('_interpolated_morphometrics.csv'):
        df = pd.read_csv(os.path.join(morphometric_results_dir, file))
        interpolated_morphometrics_df = pd.concat([interpolated_morphometrics_df, df], ignore_index=True)

# Keep only subjects included in the include_t2_subjects list 
interpolated_morphometrics_df = interpolated_morphometrics_df[interpolated_morphometrics_df["subject"].isin(include_t2_subjects["participant_id"])].reset_index(drop=True)

# Remove the last point (spinal cord tip) for each subject
idx = interpolated_morphometrics_df.groupby("subject")["VertLevel"].idxmax()
interpolated_morphometrics_df = interpolated_morphometrics_df.drop(idx).reset_index(drop=True)

# Remove age and sex columns if they exist
if 'age' in interpolated_morphometrics_df.columns:
    interpolated_morphometrics_df = interpolated_morphometrics_df.drop(columns=['age'])
if 'sex' in interpolated_morphometrics_df.columns:
    interpolated_morphometrics_df = interpolated_morphometrics_df.drop(columns=['sex'])

In [235]:
# Add sex and age columns to the DataFrame (using participants.tsv)
participants_info = pd.read_csv(participants_info_path, sep='\t')
participants_info = participants_info.rename(columns={'participant_id': 'subject'})

participants_info = participants_info[['subject', 'age', 'sex']]
interpolated_morphometrics_df = interpolated_morphometrics_df.merge(participants_info, on='subject', how='left')

print("Number of subjects:", interpolated_morphometrics_df["subject"].nunique())

Number of subjects: 93

In [236]:
interpolated_morphometrics_df

,subject,VertLevel,DistancePMJ,CSA,AP_diameter,RL_diameter,eccentricity,solidity,height,weight,age,sex
0,sub-232,1.0,26.750000,61.858208,8.043682,9.728889,0.561541,0.968981,1.524,36.287390,11,M
1,sub-232,1.1,28.354000,59.698281,7.788287,9.721150,0.596294,0.968883,1.524,36.287390,11,M
2,sub-232,1.2,29.958000,57.825237,7.534657,9.747406,0.634003,0.978817,1.524,36.287390,11,M
3,sub-232,1.3,31.562000,57.367667,7.469191,9.773150,0.644820,0.976812,1.524,36.287390,11,M
4,sub-232,1.4,33.166000,57.215116,7.385822,9.867722,0.662511,0.968851,1.524,36.287390,11,M
...,...,...,...,...,...,...,...,...,...,...,...,...
18064,sub-215,19.8,389.712000,9.206335,3.219219,3.500992,0.354624,0.983851,1.651,90.718474,16,F
18065,sub-215,19.9,392.471000,7.420212,2.616683,3.363068,0.624733,0.973006,1.651,90.718474,16,F
18066,sub-215,20.0,395.230000,8.559618,3.175002,3.272243,0.390830,0.976252,1.651,90.718474,16,F
18067,sub-215,20.1,398.164869,5.440488,2.494596,2.560332,0.609534,0.960072,1.651,90.718474,16,F
18068,sub-215,20.2,401.099739,2.323164,1.418506,1.340934,0.618733,0.942873,1.651,90.718474,16,F

### 1.6 Create dataframe containing per-slice morphometrics
Load the CSV files containing per-slice morphometrics (ending with `_per_slice.csv`) and create a single dataframe containing all participants

In [237]:
# Initialize an empty DataFrame to store per slice morphometric values
per_slice_df = pd.DataFrame()

# Load the CSV files containing morphometric values of each subject and add to a single dataframe
for file in os.listdir(morphometric_results_dir):
    if file.endswith('_per_slice.csv'):
        df = pd.read_csv(os.path.join(morphometric_results_dir, file))
        df = df.dropna(subset=["MEAN(area)"]) # remove rows where the CSA is NaN
        per_slice_df = pd.concat([per_slice_df, df], ignore_index=True)

# Add subject column from the 'Filename' column
for index, row in per_slice_df.iterrows():
    filename = row['Filename']
    filename = Path(filename)
    
    # Subject folder is the parent directory before "anat"
    subject_id = filename.parts[-3]

    # Add to the dataframe
    per_slice_df.loc[index, 'subject'] = subject_id

# Keep only subjects included in the include_t2_subjects list 
per_slice_df = per_slice_df[per_slice_df["subject"].isin(include_subjects_with_sc_tip["participant_id"])].reset_index(drop=True)

print("Number of subjects:", per_slice_df["subject"].nunique())

Number of subjects: 79

In [238]:
per_slice_df

,Timestamp,SCT Version,Filename,Slice (I->S),VertLevel,DistancePMJ,MEAN(area),STD(area),MEAN(angle_AP),STD(angle_AP),...,STD(diameter_RL),MEAN(eccentricity),STD(eccentricity),MEAN(orientation),STD(orientation),MEAN(solidity),STD(solidity),SUM(length),Normalized_PMJ_SCtip,subject
0,2026-07-02 19:52:53,7.1,/Users/samuellestonge/Documents/datasets/phila...,31,NaN,399.49,1.056132,0.0,3.719145,0.0,...,0.0,0.816540,0.0,82.838640,0.0,1.000000,0.0,0.832135,1.000000,sub-178
1,2026-07-02 19:52:53,7.1,/Users/samuellestonge/Documents/datasets/phila...,32,NaN,398.67,1.272177,0.0,2.374496,0.0,...,0.0,0.807606,0.0,86.788265,0.0,0.950000,0.0,0.830907,0.997947,sub-178
2,2026-07-02 19:52:53,7.1,/Users/samuellestonge/Documents/datasets/phila...,33,NaN,397.84,2.469509,0.0,1.212425,0.0,...,0.0,0.657209,0.0,87.974934,0.0,0.937500,0.0,0.828816,0.995870,sub-178
3,2026-07-02 19:52:53,7.1,/Users/samuellestonge/Documents/datasets/phila...,34,NaN,397.02,3.716141,0.0,0.234627,0.0,...,0.0,0.645285,0.0,49.601837,0.0,0.974790,0.0,0.825805,0.993817,sub-178
4,2026-07-02 19:52:53,7.1,/Users/samuellestonge/Documents/datasets/phila...,35,NaN,396.20,4.348797,0.0,-0.558061,0.0,...,0.0,0.412828,0.0,0.000000,0.0,0.972414,0.0,0.823432,0.991764,sub-178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36429,2026-07-03 00:23:43,7.1,/Users/samuellestonge/Documents/datasets/phila...,487,NaN,18.40,107.409957,0.0,-8.251720,0.0,...,0.0,0.401140,0.0,33.727813,0.0,0.973672,0.0,0.810261,0.046071,sub-216
36430,2026-07-03 00:23:43,7.1,/Users/samuellestonge/Documents/datasets/phila...,488,NaN,17.52,116.597987,0.0,0.325899,0.0,...,0.0,0.427596,0.0,54.224310,0.0,0.963417,0.0,0.803847,0.043868,sub-216
36431,2026-07-03 00:23:43,7.1,/Users/samuellestonge/Documents/datasets/phila...,489,NaN,16.63,113.443641,0.0,12.576045,0.0,...,0.0,0.508790,0.0,64.156617,0.0,0.968764,0.0,0.820915,0.041640,sub-216
36432,2026-07-03 00:23:43,7.1,/Users/samuellestonge/Documents/datasets/phila...,490,NaN,15.73,94.889056,0.0,26.918391,0.0,...,0.0,0.625898,0.0,82.159181,0.0,0.974653,0.0,0.898818,0.039386,sub-216
36433,2026-07-03 00:23:43,7.1,/Users/samuellestonge/Documents/datasets/phila...,491,NaN,14.82,59.615507,0.0,40.683121,0.0,...,0.0,0.762183,0.0,89.747337,0.0,0.955675,0.0,1.086740,0.037108,sub-216

### 2. Plotting functions

#### 2.1 Function to plot morphometrics per vertebral levels

In [239]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import webbrowser

def plot_morphometrics(df, morphometric_name_in_csv, morphometric_display_name, sex=None):

    # Assign a color to each age in the dataframe
    unique_ages = sorted(df['age'].unique())

    # Get 12 evenly spaced colors from a colormap
    colorscale = px.colors.diverging.Portland
    num_colors = 12
    color_gradient = px.colors.sample_colorscale(colorscale, [i / (num_colors - 1) for i in range(num_colors)])

    # Sort the ages and assign a color from the gradient
    color_map = {age: color_gradient[i] for i, age in enumerate(unique_ages)}
                 
    # Filter by sex (optional)
    if sex is not None:
        if 'sex' not in df.columns:
            raise ValueError("Column 'sex' not found in dataframe.")
        df = df[df['sex'] == sex].copy()

    # Initialize figure
    fig = go.Figure()

    # Plot one line per subject
    for subject, sub_df in df.groupby('subject'):

        sub_df = sub_df.sort_values('VertLevel')

        age = sub_df['age'].iloc[0]
        color = color_map[age]

        fig.add_trace(go.Scatter(
            x=sub_df['VertLevel'],
            y=sub_df[morphometric_name_in_csv],
            mode='lines',
            line=dict(color=color, width=1),
            opacity=0.7,
            name=str(age),
            legendgroup=str(age),
            showlegend=False
        ))

    for age in unique_ages:
        fig.add_trace(go.Scatter(
            x=[None],
            y=[None],
            mode='lines',
            line=dict(color=color_map[age], width=2),
            name=f'{age}',
            showlegend=True
        ))

    # Layout
    fig.update_layout(
        width=1000,
        height=600,
        title=f" ",
        xaxis_title='Vertebral Level',
        xaxis_title_font=dict(size=20, color='black', family='Arial', weight='bold'),
        yaxis_title=morphometric_display_name,
        yaxis_title_font=dict(size=20, color='black', family='Arial', weight='bold'),
        legend_title='Age',
        legend_title_font=dict(size=16, color='black', family='Arial', weight='bold'),
        legend_font=dict(size=14, color='black', family='Arial'),
        xaxis_tickangle=-45,
        template='plotly_white',
    )
    
    # Map VertLevel numbers to anatomical labels
    vertebral_label_map = {
        0.0: "PMJ", 1.0: "C1", 2.0: "C2", 3.0: "C3", 4.0: "C4", 
        5.0: "C5", 6.0: "C6", 7.0: "C7", 8.0: "T1", 9.0: "T2", 
        10.0: "T3", 11.0: "T4", 12.0: "T5", 13.0: "T6", 14.0: "T7", 
        15.0: "T8", 16.0: "T9", 17.0: "T10", 18.0: "T11", 19.0: "T12", 
        20.0: "L1", 21.0: "L2", 22.0: "L3", 23.0: "L4"
    }

    # Extract all vertebral levels used in the data
    all_vert_levels = sorted(df['VertLevel'].dropna().unique())

    # Filter only integer levels (to show only C1, C2, etc.)
    integer_vert_levels = [v for v in all_vert_levels if v.is_integer() and v in vertebral_label_map]

    # Map to anatomical labels
    ticktexts = [vertebral_label_map[v] for v in integer_vert_levels]

    # Update the x-axis to show anatomical vertebral labels
    fig.update_xaxes(
        tickmode='array',
        tickvals=integer_vert_levels,
        ticktext=ticktexts,
        tickcolor='black',
        tickfont=dict(size=16, color='black', family='Arial'),
        tickangle=0,
        gridcolor='rgba(0, 0, 0, 0.1)',  
        
    )
    
    fig.update_yaxes(
        gridcolor='rgba(0, 0, 0, 0.1)',
        tickcolor='black',
        tickfont=dict(size=16, color='black', family='Arial')
    )

    # Define the save path
    save_path = os.path.join('..', 'figures', f'{morphometric_name_in_csv}_vs_Vert_Levels.html')

    # Save the figure to an HTML file
    fig.write_html(save_path)

    # Open the file in the default web browser
    # webbrowser.open(f'file://{os.path.abspath(save_path)}')

    # Show the figure in the notebook as well
    fig.show()

#### 2.2 Function to plot the average morphometrics for each age, per vertebral level

In [240]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import webbrowser

def plot_average_morphometrics(df, morphometric_name_in_csv, morphometric_display_name, sex=None):

    """
    This function plots the average morphometrics per age (each curve represents the average of an age between 6 and 17.)
    """

    # Assign a color to each age in the dataframe
    unique_ages = sorted(df['age'].unique())

    # Get 12 evenly spaced colors from a colormap
    colorscale = px.colors.diverging.Portland
    num_colors = 12
    color_gradient = px.colors.sample_colorscale(colorscale, [i / (num_colors - 1) for i in range(num_colors)])

    # Sort the ages and assign a color from the gradient
    color_map = {age: color_gradient[i] for i, age in enumerate(unique_ages)}
                 
    # Filter by sex (optional)
    if sex is not None:
        if 'sex' not in df.columns:
            raise ValueError("Column 'sex' not found in dataframe.")
        df = df[df['sex'] == sex].copy()

    # Compute mean and std dev per age and vertebral level
    grouped = df.groupby(['age', 'VertLevel'])[morphometric_name_in_csv].agg(['mean', 'std']).reset_index()

    # Initialize figure
    fig = go.Figure()

    # Plot each age group
    for age in unique_ages:
        group = grouped[grouped['age'] == age].sort_values('VertLevel')

        x = group['VertLevel']
        y_mean = group['mean']
        y_std = group['std']

        y_upper = y_mean + y_std
        y_lower = y_mean - y_std
        color = color_map[age]

        # Add mean line
        fig.add_trace(go.Scatter(
            x=x,
            y=y_mean,
            mode='lines',
            name=f'{age}',
            line=dict(color=color, width=2),
            marker=dict(size=6),
            legendgroup=f'Age {age}'
        ))

    # Layout
    fig.update_layout(
        width=1000,
        height=600,
        title=f" ",
        xaxis_title='Vertebral Level',
        xaxis_title_font=dict(size=20, color='black', family='Arial', weight='bold'),
        yaxis_title=morphometric_display_name,
        yaxis_title_font=dict(size=20, color='black', family='Arial', weight='bold'),
        legend_title='Age',
        legend_title_font=dict(size=16, color='black', family='Arial', weight='bold'),
        legend_font=dict(size=14, color='black', family='Arial'),
        xaxis_tickangle=-45,
        template='plotly_white',
    )
    
    # Map VertLevel numbers to anatomical labels
    vertebral_label_map = {
        0.0: "PMJ", 1.0: "C1", 2.0: "C2", 3.0: "C3", 4.0: "C4", 
        5.0: "C5", 6.0: "C6", 7.0: "C7", 8.0: "T1", 9.0: "T2", 
        10.0: "T3", 11.0: "T4", 12.0: "T5", 13.0: "T6", 14.0: "T7", 
        15.0: "T8", 16.0: "T9", 17.0: "T10", 18.0: "T11", 19.0: "T12", 
        20.0: "L1", 21.0: "L2", 22.0: "L3", 23.0: "L4"
    }

    # Extract all vertebral levels used in the data
    all_vert_levels = sorted(df['VertLevel'].dropna().unique())

    # Filter only integer levels (to show only C1, C2, etc.)
    integer_vert_levels = [v for v in all_vert_levels if v.is_integer() and v in vertebral_label_map]

    # Map to anatomical labels
    ticktexts = [vertebral_label_map[v] for v in integer_vert_levels]

    # Update the x-axis to show anatomical vertebral labels
    fig.update_xaxes(
        tickmode='array',
        tickvals=integer_vert_levels,
        ticktext=ticktexts,
        tickcolor='black',
        tickfont=dict(size=16, color='black', family='Arial'),
        tickangle=0,
        gridcolor='rgba(0, 0, 0, 0.1)',  
        
    )
    
    fig.update_yaxes(
        gridcolor='rgba(0, 0, 0, 0.1)',
        tickcolor='black',
        tickfont=dict(size=16, color='black', family='Arial')
    )

    # Define the save path
    save_path = os.path.join('..', 'figures', f'{morphometric_name_in_csv}_vs_Vert_Levels.html')

    # Save the figure to an HTML file
    fig.write_html(save_path)

    # Open the file in the default web browser
    # webbrowser.open(f'file://{os.path.abspath(save_path)}')

    # Show the figure in the notebook as well
    fig.show()

### 2.3 Function to plot morphometrics per spinal cord landmarks (PMJ + spinal cord tip)

In [241]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import webbrowser
import os

def plot_morphometrics_SC_landmarks(df, SC_landmark_normalization, morphometric_name_in_csv, morphometric_display_name):

    fig = go.Figure()

    # Get unique subjects
    unique_subjects = sorted(df['subject'].unique())

    # Create a color gradient
    colorscale = px.colors.sequential.Viridis
    num_colors = len(unique_subjects)
    color_gradient = px.colors.sample_colorscale(
        colorscale,
        [i / max(num_colors - 1, 1) for i in range(num_colors)]
    )

    color_map = {
        subject: color_gradient[i]
        for i, subject in enumerate(unique_subjects)
    }

    # Loop over subjects
    for subject in unique_subjects:

        subject_df = df[df['subject'] == subject]

        x = subject_df[SC_landmark_normalization]
        y = subject_df[morphometric_name_in_csv]

        fig.add_trace(go.Scatter(
            x=x,
            y=y,
            mode='lines',
            name=f'{subject}',
            line=dict(color=color_map[subject], width=2),
            opacity=0.8
        ))

    # Layout
    fig.update_layout(
        width=1000,
        height=600,
        xaxis_title='PMJ to SC tip',
        yaxis_title=morphometric_display_name,
        template='plotly_white',
        legend_title='Subjects'
    )

    # # Save figure in HTML format : 
    # save_path = os.path.join('..', 'figures',
    #                          f'{morphometric_name_in_csv}_vs_Vert_Levels.html')
    # fig.write_html(save_path)
    # webbrowser.open(f'file://{os.path.abspath(save_path)}')
    
    # Show figure in notebook : 
    fig.show()

### 2.3 Function that interpolates each subject's curve onto a common grid (0 to 1)

This is because, in the per_slice.csv files, not every participant has the same number of values interpolated between 0 and 1 (from the PMJ to the SC tip). To simplify the analyses, we created a function to interpolate 200 points between 0 to 1, so that each participant will have the same number of points to trace the curve. This number of points will correspond to number of maximum number of slices between the PMJ and the SC tip across all participants.

In [242]:
import numpy as np
import pandas as pd

def interpolate_curves(df, subject_col, pos_col, csa_col):
    """
    Interpolates each subject's curve onto a common grid (0 to 1) with the same number of points. 

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe with subject, position, and CSA columns
    subject_col : str
        Column name for subject IDs
    pos_col : str
        Column name for normalized positions (values between 0 and 1)
    csa_col : str
        Column name for CSA values
    n_points : int
        Number of points in the interpolated grid (default: 200)

    Returns
    -------
    df_interp : pandas.DataFrame
        DataFrame in long format with columns:
        [subject_col, pos_col, csa_col]
        where pos_col now has n_points equally spaced values from 0 to 1 per subject
    """

    subjects = df[subject_col].unique() # Get the list of subjects

    # Step 1 : Get the number of points (corresponding to the maximum number of slices between the PMJ and the SC across the dataset)

    for subj in subjects:
        # Get the subset of the dataset corresponding to that subject
        subj_df = df[df[subject_col] == subj]
        # Get number of values (points) for that subject in the "pos_col" column 
        n_points = subj_df[pos_col].notna().sum()


    # Step 2 : Define a common normalized grid between 0 and 1, with n_points as the number of points,
    # so every subject’s curve can be interpolated onto the same positions on the x axis
    x_common = np.linspace(0, 1, n_points)
    data_list = []


    # Step 3 : Resample each subject's CSA values onto the common normalized grid, so that each subject
    # has the same number of points, in the same x position (between 0 and 1)

    for subj in subjects:
        sub = df[df[subject_col] == subj].sort_values(pos_col)
        x = sub[pos_col].values
        y = sub[csa_col].values

        # Interpolate onto common grid
        y_interp = np.interp(x_common, x, y)

        # After interpolation, keep only the region where the subject originally had data
        # This is to avoid having horizontal lines on graphs from PMJ distance = 0
        y_interp[(x_common < x.min()) | (x_common > x.max())] = np.nan  

        df_subj = pd.DataFrame({
            subject_col: subj,
            pos_col: x_common,
            csa_col: y_interp
        })
        data_list.append(df_subj)

    df_interp = pd.concat(data_list, ignore_index=True)
    
    return df_interp

### 3. Plots

#### 3.1 Spinal cord cross-sectional area (CSA)

##### 3.1.1 All participants

In [243]:
plot_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)')
plot_average_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)')

##### 3.1.2 Female

In [244]:
plot_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)', sex='F')
plot_average_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)', sex='F')

##### 3.1.3 Male

In [245]:
plot_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)', sex='M')
plot_average_morphometrics(interpolated_morphometrics_df, 'CSA','CSA (mm²)', sex='M')

#### 3.2 Antero-posterior (AP) diameter, right-left (RL) diameter

##### 3.2.1 All participants

In [246]:
plot_average_morphometrics(interpolated_morphometrics_df, 'AP_diameter', 'AP Diameter (mm)')
plot_average_morphometrics(interpolated_morphometrics_df, 'RL_diameter', 'Transverse Diameter (mm)')
plot_morphometrics(interpolated_morphometrics_df, 'AP_diameter', 'AP Diameter (mm)')
plot_morphometrics(interpolated_morphometrics_df, 'RL_diameter', 'Transverse Diameter (mm)')

##### 3.2.2 Female

In [247]:
plot_average_morphometrics(interpolated_morphometrics_df, 'AP_diameter', 'AP Diameter (mm)', sex='F')
plot_average_morphometrics(interpolated_morphometrics_df, 'RL_diameter', 'Transverse Diameter (mm)', sex='F')

##### 3.2.3 Male

In [248]:
plot_average_morphometrics(interpolated_morphometrics_df, 'AP_diameter', 'AP Diameter (mm)', sex='M')
plot_average_morphometrics(interpolated_morphometrics_df, 'RL_diameter', 'Transverse Diameter (mm)', sex='M')

#### 3.3 CSA vs spinal cord length (normalized from PMJ to SC tip)

In [249]:
# interpolate to get the same number of points for every subject
per_slice_df_interp = interpolate_curves(per_slice_df, subject_col='subject', pos_col='Normalized_PMJ_SCtip', csa_col='MEAN(area)')
plot_morphometrics_SC_landmarks(per_slice_df_interp, 'Normalized_PMJ_SCtip', 'MEAN(area)','CSA (mm²)')

### 4. Statistical analyses

#### 4.1 Linear mixed model

This model takes into consideration the repeated measures of each subject (measures for each vertebral level)

##### 4.1.1 With age

In [250]:
import statsmodels.formula.api as smf 

cols = ["CSA", "age", "VertLevel", "subject"] 
df = interpolated_morphometrics_df[cols].dropna().copy() 
df["subject"] = df["subject"].astype("category") 

model = smf.mixedlm( "CSA ~ age + VertLevel", data=df, groups="subject" ) 

result = model.fit() 
print(result.summary())

          Mixed Linear Model Regression Results
=========================================================
Model:            MixedLM Dependent Variable: CSA
No. Observations: 18069   Method:             REML
No. Groups:       93      Scale:              147.4831
Min. group size:  121     Log-Likelihood:     -70927.5953
Max. group size:  207     Converged:          Yes
Mean group size:  194.3
---------------------------------------------------------
             Coef.  Std.Err.    z     P>|z| [0.025 0.975]
---------------------------------------------------------
Intercept    58.889    2.352   25.036 0.000 54.279 63.500
age           0.843    0.185    4.559 0.000  0.481  1.206
VertLevel    -2.085    0.016 -129.958 0.000 -2.117 -2.054
subject Var  29.281    0.368
=========================================================

##### 4.1.2 With age and sex

In [251]:
import statsmodels.formula.api as smf 

cols = ["CSA", "age", "sex", "VertLevel", "subject"] 
df = interpolated_morphometrics_df[cols].dropna().copy() 
df["sex"] = df["sex"].astype("category") 
df["subject"] = df["subject"].astype("category") 

model = smf.mixedlm( "CSA ~ age + sex + VertLevel", data=df, groups="subject" ) 

result = model.fit() 
print(result.summary())

          Mixed Linear Model Regression Results
=========================================================
Model:            MixedLM Dependent Variable: CSA
No. Observations: 18069   Method:             REML
No. Groups:       93      Scale:              147.4832
Min. group size:  121     Log-Likelihood:     -70926.4747
Max. group size:  207     Converged:          Yes
Mean group size:  194.3
---------------------------------------------------------
             Coef.  Std.Err.    z     P>|z| [0.025 0.975]
---------------------------------------------------------
Intercept    59.016    2.392   24.671 0.000 54.328 63.705
sex[T.M]     -0.398    1.155   -0.345 0.730 -2.663  1.866
age           0.847    0.186    4.549 0.000  0.482  1.212
VertLevel    -2.085    0.016 -129.957 0.000 -2.117 -2.054
subject Var  29.574    0.373
=========================================================

##### 4.1.3 With age, sex, height and weight

In [252]:
import statsmodels.formula.api as smf 

cols = ["CSA", "age", "sex", "height", "weight", "VertLevel", "subject"] 
df = interpolated_morphometrics_df[cols].dropna().copy() 
df["sex"] = df["sex"].astype("category") 
df["subject"] = df["subject"].astype("category") 

model = smf.mixedlm( "CSA ~ age + sex + height + weight + VertLevel", data=df, groups="subject" ) 

result = model.fit() 
print(result.summary())

          Mixed Linear Model Regression Results
=========================================================
Model:            MixedLM Dependent Variable: CSA
No. Observations: 17337   Method:             REML
No. Groups:       89      Scale:              147.0818
Min. group size:  121     Log-Likelihood:     -68026.1407
Max. group size:  207     Converged:          Yes
Mean group size:  194.8
---------------------------------------------------------
            Coef.  Std.Err.    z     P>|z|  [0.025 0.975]
---------------------------------------------------------
Intercept   56.481    7.957    7.098 0.000  40.886 72.076
sex[T.M]     0.337    1.216    0.277 0.782  -2.046  2.720
age          0.469    0.252    1.864 0.062  -0.024  0.962
height       0.770    6.775    0.114 0.909 -12.509 14.050
weight       0.121    0.054    2.239 0.025   0.015  0.227
VertLevel   -2.076    0.016 -127.164 0.000  -2.108 -2.044
subject Var 28.536    0.374
=========================================================